version: "3.4"
services:
  clash-ws-1:
    image: clash:latest
    container_name: clash-1
    hostname: clash-1
    environment:
      - TZ="Asia/Shanghai"
    volumes:
      - ./config:/opt/config
      - ./logs/:/opt/logs/
    networks:
      - default_bridge
  go-proxy2:
    image: clash:latest
    container_name: clash-2
    hostname: clash-2
    environment:
      - TZ="Asia/Shanghai"
    volumes:
      - ./config:/opt/config
      - ./logs/:/opt/logs/
    networks:
      - default_bridge
networks:
  default_bridge:
    external: true
